sudo: false
language: java

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

script: mvn install

after_success:
  - mvn coveralls:report

cache:
  directories:
  - $HOME/.m2